# articles_data.py

class ArticleData:
    articles = [
        {
            "id": 1,
            "title": "Cele mai recente tehnologii în domeniul AI",
            "content": "În informatică, inteligența artificială (IA) este inteligența "
                       "mașinilor, spre deosebire de inteligența naturală de la oameni "
                       "și animale. Informatica definește cercetarea IA ca studiu al "
                       "„agenților inteligenți⁠(d)"": orice dispozitiv care își percepe "
                       "mediul și efectuează acțiuni care maximizează șansa de a-și "
                       "atinge cu succes obiectivele. Mai exact, "
                       "Kaplan și Haenlein definesc IA ca fiind „capacitatea unui "
                       "sistem de a interpreta corect datele externe, de a învăța din "
                       "astfel de date și de a folosi ceea ce a învățat pentru a-și "
                       "atinge obiective și sarcini specifice printr-o adaptare "
                       "flexibilă”. Termenul „inteligență artificială” este "
                       "utilizat colocvial pentru a descrie mașinile care imită "
                       "funcțiile cognitive pe care le asociază oamenii cu alte minți "
                       "umane, cum ar fi „învățarea” și „rezolvarea problemelor”."
                       " Inteligența artificială implică dezvoltarea de algoritmi și "
                       "modele care permit mașinilor să-și perceapă mediul, "
                       "să își motiveze mediul și să facă acțiuni adecvate pentru a "
                       "atinge obiective specifice. Acești algoritmi folosesc volume "
                       "mari de date și tehnici avansate, cum ar fi învățarea "
                       "automată, învățarea profundă, procesarea limbajului natural și "
                       "viziunea computerizată.Află mai multe despre ultimele tendințe "
                       "și tehnologii din domeniul inteligenței "
                       "artificiale.Inteligența artificială fără cod, cu interfețele "
                       "sale ușoare de tip drag-and-drop, va permite oricărei companii "
                       "să-și folosească puterea pentru a crea produse și servicii mai "
                       "inteligente. Vedem deja această tendință pe piața de retail. "
                       "Stitch Fix folosește algoritmi activați cu inteligență "
                       "artificială pentru a recomanda clienților săi haine care se "
                       "potrivesc cu mărimile și gusturile acestora. Cumpărăturile și "
                       "livrarea autonome, fără contact, vor fi, de asemenea, "
                       "o tendință uriașă pentru 2023. IA va face mai ușoare pentru "
                       "consumatori plata și primirea de bunuri și servicii. IA va "
                       "spori, de asemenea, aproape fiecare loc de muncă din fiecare "
                       "proces de afaceri din industrii. Mai mulți comercianți cu "
                       "amănuntul vor folosi inteligența artificială pentru a gestiona "
                       "și automatiza procesele complexe de gestionare a stocurilor "
                       "care au loc în culise, astfel încât tendințele de comoditate "
                       "cum ar fi buy-online-pickup-at-curbside (BOPAC), "
                       "buy-online-pickup-in-store (BOPIS), "
                       "iar buy-online-return-in-store (BORIS) va deveni un lucru "
                       "standard. Inteligența artificială va fi, de asemenea, "
                       "motorul din spatele celor mai noi inițiative de livrare "
                       "autonomă pe care comercianții cu amănuntul le pilotează și le "
                       "lansează, iar din ce în ce mai mulți lucrători din retail vor "
                       "trebui să se obișnuiască să lucreze alături de mașinării. "
        },
        {
            "id": 2,
            "title": "Arta abstractă și expresionistă în secolul XXI",
            "content": "Renașterea a debutat în secolele XIV-XVI, perioada Evului "
                       "Mediu Târziu, în Florența - Italia și s-a răspândit în "
                       "restul Europei. Această mișcare culturală reprezintă "
                       "înflorirea inovatoare a literaturii latine și autohtone, "
                       "începând din secolul al XIV-lea, când erau cercetate "
                       "sursele literare din antichitatea clasică creditată lui "
                       "Francesco Petrarca. Dezvoltarea în pictură a tehnicilor de "
                       "perspectivă, de acordare a unei realități mult mai "
                       "naturale a dus și la o reformă educațională. Schimbările "
                       "Renașterii nu au fost implementate uniform de întreaga "
                       "Europă, deși apariția tiparului a accelerat difuzarea "
                       "ideilor în secolul al XV-lea. Descoperă operele cele mai "
                       "remarcabile și inovative ale artiștilor din secolul XXI." "Arta abstractă este denumirea pe "
                       "care, începând cu cel de-al treilea deceniu al secolului al XX-lea,"
                       "și-o revendică o serie de tendințe, de grupări, de creații - în general diverse, "
                       "succedându-se nu fără o anumită atitudine polemică - care au la bază un protest împotriva "
                       "academismului și naturalismului, îndepărtând din imaginea plastică elementele lumii vizibile, "
                       "redate până atunci din așa zisă artă figurativă, și așezând în locul lor un sistem de semne, "
                       "linii, pete, volumi, ce ar trebui să exprime, în formă pură, acțiunea raționalității și "
                       "sensibilității umane dar si gândurile cele mai ascunse și unele detalii ale personalității "
                       "acestora ce sunt adânc îngropate în suflet așteptând să fie scoase la iveală. "

                       "Plecând de la ideea că arta plastică, arhitectura și muzica sunt prin excelență abstracte - "
                       "ele presupunând în"
                       "același timp o sumă de legături cu irealul, și fiind, de regulă, neacceptate drept "
                       "construcții, ci ansambluri controlate de logică - primii artiști atrași de abstracționism își "
                       "manifestă, cu un sentiment de eliberare, întreaga încărcătură emoțională, sentimentala si "
                       "senzitiva."
        },
        {
            "id": 3,
            "title": "Cele mai controversate discutii despre AI",
            "content": "Subiectele controversate de dezbatere sunt subiecte care pot "
                       "stârni opinii puternice și dezacorduri între oameni cu "
                       "convingeri și valori diferite. Aceste subiecte pot acoperi "
                       "diverse subiecte, cum ar fi probleme sociale, politică, "
                       "etică și cultură și pot contesta credințele tradiționale sau "
                       "normele stabilite" "Un lucru care face ca aceste subiecte să fie "
                       "controversate este că adesea nu există un consens clar sau un "
                       "acord între oameni, ceea ce poate duce la dezbateri și dezacorduri. "
                       "Fiecare persoană poate avea propria interpretare a faptelor sau "
                       "valorilor care îi influențează perspectiva. Este dificil pentru "
                       "toți să ajungă la o rezoluție sau un acord." "Treaba cu A.I. se complică atunci când toată "
                       "lumea se pricepe la ce este, ce înseamnă și cum anume ne va afecta această tehnologie, "
                       "la fel cum se pricepe la fotbal, pescuit, vinuri și așa mai departe. Eu știu că nu mă pricep, "
                       "dar știu și că această tehnologie poate crea o sumă întreagă de instrumente de care trebuie "
                       "să ne folosim, dacă vrem să continuăm să progresăm. "

                       "Privind din această perspectivă, nu înțeleg de ce anume trebuie să se opunem tehnologiei "
                       "A.I., doar pentru că unii"
                       "sunt speriați în mod irațional de perspectivele sale de evoluție și accept ideea că este "
                       "nevoie de un set de reglementări care să ne asigure – în anumite limite – că dezvoltarea "
                       "instrumentelor A.I. va veni în sprijinul omenirii, al protejării libertăților individuale și "
                       "demnității umane."
        },
        {
            "id": 4,
            "title": "Inteligența artificială amplifică amenințările de securitate",
            "content": "Viitorul nu se anunţă deloc simplu pentru "
                       "experţii din cybersecurity, iar creşterea "
                       "numărului de specialişti IT şi nivelul lor "
                       "de expertiză şi pregătire pentru a face faţă "
                       "atacurilor trebuie să fie una dintre "
                       "principalele măsuri adoptate de corporaţii "
                       "şi guverne din întreaga lume. Din fericire, "
                       "există în prezent multe resurse şi "
                       "iniţiative care contribuie la formarea şi "
                       "evoluţia specialiştilor din acest domeniu. "
                       "Una dintre acestea este şi DefCamp unde, "
                       "din 2011, sunt analizate în fiecare an cele "
                       "mai noi tendinţe şi soluţii de "
                       "cybersecurity. Astăzi, DefCamp este un hub "
                       "al inovaţiei şi al colaborării în domeniul "
                       "securităţii cibernetice, care adună la "
                       "fiecare ediţie mii de participanţi din toată "
                       "lumea, atât pasionaţi de securitate "
                       "cibernetică, cât şi experţi, reprezentanţi "
                       "ai instituţiilor, lideri ai companiilor şi "
                       "ONG-urilor, şi studenţi. În plus, "
                       "este şi o iniţiativă de a simplifica "
                       "activitatea specialiştilor în securitate, "
                       "dar, mai ales, de a împiedica şi limita "
                       "eficienţa atacurilor cibernetice.""Inteligența artificială pentru securitate cibernetică "
                       "funcționează prin evaluarea volumelor uriașe de date din mai multe surse, pentru a identifica "
                       "modelele de activitate dintr-o organizație, cum ar fi momentul și locul în care se conectează "
                       "utilizatorii, volumele de trafic, precum și dispozitivele și aplicațiile în cloud pe care le "
                       "utilizează angajații. După ce înțelege ce este tipic, poate identifica un comportament "
                       "anormal care poate necesita o investigare. Pentru a menține confidențialitatea, datele unei "
                       "organizații nu sunt utilizate în răspunsurile inteligenței artificiale către alte "
                       "organizații. În schimb, inteligența artificială utilizează investigarea globală a "
                       "amenințărilor, sintetizată de la mai multe organizații."

                       "Inteligența artificială utilizează algoritmi de învățare programată pentru a învăța continuu "
                       "pe baza datelor pe care"
                       "le evaluează sistemul. Atunci când inteligența artificială generativă identifică anumite "
                       "amenințări cibernetice cunoscute, cum ar fi malware, poate ajuta la punerea în context și "
                       "înțelegerea mai ușoară a analizei amenințărilor, generând text nou sau imagini care să "
                       "descrie ce se întâmplă."

                       "Oamenii sunt în continuare esențiali în securitatea cibernetică, dar inteligența artificială "
                       "îi ajută să-și dezvolte competențele și să identifice și să rezolve mai rapid amenințările."


        },
        {
            "id": 5,
            "title": "Noua revoluţie care va hotărî cine va conduce lumea",
            "content": "Majoritatea analiştilor tratează problema IA ca o "
                       "problemă a cursei tehnologice dintre SUA şi China. "
                       "Fără îndoială, mult din această competiţie se va "
                       "consuma în disputa directă americano-chineză, "
                       "date fiind atuurile de care am vorbit mai sus.  Se "
                       "neglijează, după opinia noastră, relevanţa prezenţei "
                       "ruseşti în această competiţie. Când Vladimir Putin "
                       "spune: „cine va deveni lider în domeniul inteligenţei "
                       "artificială, va conduce lumea” nu ne închipuim că a "
                       "făcut o asemenea afirmaţie de pe poziţia unui "
                       "comentator detaşat. Nu, a făcut-o ştiind că Rusia are "
                       "şi ea atuurile sale, mai mult că are anumite poziţii "
                       "deja câştigate. Nu este îndoială în această privinţă. "
                       "Specialiştii în securitate cibernetică trebuie să fie mereu cu un pas înaintea atacatorilor "
                       "pentru a putea elabora soluţii de securitate eficiente, indiferent de versatilitatea şi "
                       "complexitatea atacurilor. Ceea ce, în peisajul ameninţărilor cibernetice de astăzi, "
                       "este o reală provocare, dar anticiparea riscurilor şi pregătirea unui sistem de apărare "
                       "împotriva lor devine mai simplă când specialiştii în securitate sunt conectaţi la cele mai "
                       "importante tendinţe din domeniu. "
                       "Inteligenţa Artificială (AI) este, de departe, cea mai nouă tehnologie care a cunoscut deja o "
                       "expansiune uriaşă în 2023. Mai mult de atât, încă nu este clar cât de departe poate evolua, "
                       "iar vocile care atrag atenţia asupra unor posibile consecinţe negative serioase asupra "
                       "siguranţei datelor şi oamenilor devin tot mai numeroase. Aceasta poate fi folosită pentru a "
                       "creşte exponenţial complexitatea atacurilor, le permite atacatorilor să fie mult mai creativi "
                       "şi să păcălească mai bine metodele tradiţionale de protecţie. Machine Learning şi "
                       "automatizarea în ansamblu sunt arii care necesită o atenţie deosebită în viitor, "
                       "fiind tehnologii care îi pot ajuta enorm pe cei care vor să afle informaţii confidenţiale "
                       "deţinute de corporaţii sau oameni sau vor să să saboteze anumite sisteme critice."
                       "Ransomware-as-a-Service (RaaS) este o consecinţă a specializării atacatorilor şi a utilizării "
                       "unor instrumente de automatizare în scop distructiv. Atacurile de tip ransomware au crescut "
                       "mult în ultimii ani, iar măsurile bune luate de corporaţii i-au obligat pe atacatori să "
                       "devină mai creativi, ceea ce au şi făcut, graţie noilor tehnologii apărute între timp. "
                       "Astfel, există platforme de tip RaaS, dar acestea au devenit mai puternice şi pot lansa un "
                       "număr mai mare de atacuri de acest tip, iar experţii trebuie să adapteze sistemele de "
                       "protecţie în consecinţă. Aceste platforme devin tot mai numeroase şi mai specializate, "
                       "astfel că vor deveni o ameninţare tot mai serioasă. "
                       "Deepfake este o altă tactică care a evoluat pe fondul AI şi a noilor tehnologii. În prezent, "
                       "există o gamă extrem de largă de instrumente, disponibile oricui, care permit un nivel înalt "
                       "al falsificării unor imagini sau voci. Experţii în dezinformare şi manipulare se simt "
                       "probabil extrem de mulţumiţi să vadă acum multitudinea de opţiuni pe care le au la "
                       "dispoziţie. Corporaţiile şi oamenii trebuie să fie mereu atenţi atunci când vin în contact cu "
                       "astfel de atacuri, având în vedere nivelul înalt de complexitate la care au ajuns. Un expert "
                       "în astfel de tactici poate crea imaginea unui CEO, de exemplu, care să transmită anumite "
                       "mesaje false către angajaţi, cu posibile consecinţe negative extrem de serioase. Iar "
                       "consecinţele pot fi infinit mai grave când vorbim despre astfel de mesaje transmise de către "
                       "imaginea unor şefi de state către populaţie. "
                       "5G şi Internet of Things sunt alte zone complicate în ceea ce priveşte securitatea "
                       "cibernetică, care vor deveni şi mai complexe în viitor. Adoptarea pe scară largă a 5G va "
                       "duce, în mod implicit, la o creştere masivă a numărului de dispozitive conectate, iar asta va "
                       "contribui din plin la expansiunea Internet of Things (IoT). Desigur, totul este gândit pentru "
                       "a face viaţa mai uşoară oamenilor, dar alţii vor vedea aici multe oportunităţi de atac "
                       "cibernetic. Dezvoltarea reţelelor 5G va creşte automat şi viteza atacurilor, "
                       "iar dispozitivele IoT sunt mai vulnerabile decât altele, precum laptopuri sau smartphone, "
                       "pentru că nu au fost gândite din start cu sisteme de protecţie. Orice dispozitiv care se "
                       "poate conecta la internet, indiferent că vorbim de TV, frigidere, sisteme HVAC etc. poate "
                       "deveni ţinta unui atac. "
                       "Insider-ii vor fi folosiţi tot mai mult de atacatori în viitor, ei rămânând acea tactică "
                       "tradiţională simplă şi eficientă într-o lume tot mai complicată. Indiferent cât de mult vor "
                       "evolua sistemele de protecţie, oamenii din interior care fac jocul atacatorilor, voluntar sau "
                       "nu, vor rămâne mereu un adevărat „călcâi al lui Ahile” al oricărei organizaţii. Inclusiv "
                       "atacurile asupra lanţurilor logistice sau asupra infrastructurii critice pot fi mult mai "
                       "eficiente cu ajutorul unor oameni din interior. Aceştia ori sunt păcăliţi, ori acceptă "
                       "recompense pentru acţiuni de sabotaj sau poate fac asta din anumite convingeri politice sau "
                       "religioase. În ultima vreme observăm şi creşterea tensiunilor geopolitice, astfel că nu "
                       "trebuie să eliminăm nicio posibilitate. În faţa acestui tip de ameninţare, trebuie implicarea "
                       "masivă a unui furnizor extern de soluţii de securitate, care să poată observa din exterior "
                       "mai uşor persoanele care pot face jocul atacatorilor."
        }
    ]
